### ISSUE TITLE
[Feature] Optional MemberJoin Message to User

### ISSUE THREAD

**Issue by nikolaischunk** [BirthdayyBot/BirthdayyBot#396]
## Idea

When a User joins a server, the serverowner can enable a message, that gets sent by the Bot when a new User joins.

### ToDo
- [ ] Think of a fitting name for this feature
- [ ] Add `guild` config column
- [ ] Add config update command
- [ ] Add config reset command
- [ ] Check if user can send message to user
- [ ] Think of Message to send
- [ ] How can I send a link to the command in the correct server?

**Comment by Swiizyy** [comment]
I don't think this feature would be interesting for us given that the bot is focused on birthdays and some bots already do it very well.

**Comment by nikolaischunk** [comment]
agree
